
const taclarFee=2000;
const collectionName='taclar_interurbain';
const axes=['Libreville → Oyem → Bitam','Libreville → Lambaréné','Libreville → Mitzic'];
const axisPrices={'Libreville → Oyem → Bitam':25000,'Libreville → Lambaréné':18000,'Libreville → Mitzic':22000};
const departureTimes=['05h00','05h30','06h00','06h30','07h00','07h30','08h00','08h30','09h00','09h30','10h00','10h30','12h00','14h00','15h00','16h00','18h00'];
let db=null,docs=[],ready=false,selectedOfferId=null;
function $(id){return document.getElementById(id)}
function money(n){return Number(n||0).toLocaleString('fr-FR')+' FCFA'}
function nowLabel(){return new Date().toLocaleString('fr-FR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'})}
function byType(t){return docs.filter(d=>d.type===t).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))}
function apps(){return byType('driverApplication')}
function activeApps(){return apps().filter(a=>a.active)}
function offers(){return byType('offer')}
function requests(){return byType('request')}
function reqsForOffer(id){return requests().filter(r=>r.offerId===id)}
function liveReqsForOffer(id){return reqsForOffer(id).filter(r=>!['refused','deleted'].includes(r.status))}
function paidReqsForOffer(id){return reqsForOffer(id).filter(r=>r.status==='paid')}
function seatsTaken(offer){return liveReqsForOffer(offer.id).reduce((s,r)=>s+Number(r.seats||1),0)}
function paidSeats(offer){return paidReqsForOffer(offer.id).reduce((s,r)=>s+Number(r.seats||1),0)}
function freeSeats(offer){return Math.max(0,Number(offer.seats||0)-Number(offer.booked||0)-seatsTaken(offer))}
function phoneMask(p){p=String(p||'');return p.length>5?p.slice(0,7)+' ** ** '+p.slice(-2):'masqué'}
function statusText(s){return {submitted:'Dossier envoyé',docs_validated:'Documents validés',deposit_paid:'Caution déposée',deposit_validated:'Caution validée',active:'Chauffeur actif',pending:'Demande envoyée',confirmed:'Confirmée chauffeur - frais TACLAR à payer',paid:'Commission TACLAR payée',refused:'Refusée',deleted:'Supprimée'}[s]||s||'-'}
function fillAxisSelect(sel,empty='-- Choisir un axe --'){if(!sel)return;const v=sel.value;sel.innerHTML=`<option value="">${empty}</option>`+axes.map(a=>`<option value="${a}">${a}</option>`).join('');if(axes.includes(v))sel.value=v}
function fillTimeSelect(sel,empty='-- Choisir --'){if(!sel)return;const v=sel.value;sel.innerHTML=`<option value="">${empty}</option>`+departureTimes.map(t=>`<option value="${t}">${t}</option>`).join('');if(departureTimes.includes(v))sel.value=v}
async function addDoc(data){if(!db)throw new Error('Firebase non connecté');return db.collection(collectionName).add({...data,createdAt:Date.now(),updatedAt:Date.now()})}
async function updateDoc(id,data){if(!db)throw new Error('Firebase non connecté');return db.collection(collectionName).doc(id).set({...data,updatedAt:Date.now()},{merge:true})}
async function deleteDocHard(id){if(!db)throw new Error('Firebase non connecté');return db.collection(collectionName).doc(id).delete()}
function initFirebase(){const cfg=window.TACLAR_FIREBASE_CONFIG;if(!cfg||String(cfg.apiKey||'').includes('COLLER_')){showLoad('Firebase non configuré');return}firebase.initializeApp(cfg);db=firebase.firestore();showLoad('Connexion Firebase...');db.collection(collectionName).onSnapshot(snap=>{docs=snap.docs.map(d=>({id:d.id,...d.data()}));ready=true;showLoad('Synchronisé');setTimeout(()=>showLoad(''),900);renderPage();},err=>{showLoad('Erreur Firebase: '+err.message)})}
function showLoad(txt){let el=$('syncStatus');if(!el){el=document.createElement('div');el.id='syncStatus';el.className='loading';document.body.appendChild(el)}el.textContent=txt;el.style.display=txt?'block':'none'}
function header(active){return `<header class="hero"><div class="hero-inner"><div class="brand"><div class="logo">TACLAR</div><div><div class="axis-name">TACLAR Interurbain - V29 Firebase</div><h1>Mise en relation client-chauffeur</h1><p>Version propre Firestore : chaque page lit et écrit dans les mêmes données.</p></div></div><nav class="nav"><a class="${active==='new'?'active':''}" href="taclar_nouveau_chauffeur.html">Nouveau chauffeur</a><a class="${active==='publish'?'active':''}" href="taclar_publier_trajet.html">Publier trajet</a><a class="${active==='booking'?'active':''}" href="taclar_booking.html">Booking / Disponibilités</a><a class="${active==='client'?'active':''}" href="taclar_client.html">Client</a></nav></div></header>`}
function setShell(active,main){$('app').innerHTML=header(active)+main}
function renderPage(){const page=document.body.dataset.page;if(page==='new')renderNewDriver();else if(page==='publish')renderPublish();else if(page==='booking')renderBooking();else if(page==='client')renderClient();else renderPortal()}
function renderPortal(){setShell('portal',`<div class="card"><h2>Accès TACLAR Interurbain</h2><p>Utilise la page complète pour présenter, ou ouvre une page séparée selon le rôle.</p><div class="portal-grid"><a href="taclar_nouveau_chauffeur.html"><strong>Nouveau chauffeur</strong><p>Inscription, documents, caution et validation TACLAR.</p></a><a href="taclar_publier_trajet.html"><strong>Publier trajet</strong><p>Un chauffeur validé publie une disponibilité.</p></a><a href="taclar_booking.html"><strong>Booking / Disponibilités</strong><p>Le chauffeur traite les demandes clients.</p></a><a href="taclar_client.html"><strong>Client</strong><p>Le client cherche un axe et réserve une ou plusieurs places.</p></a></div></div>`)}
function renderNewDriver(){setShell('new',`<div class="grid two"><div class="card"><h2>Nouveau chauffeur - rejoindre TACLAR</h2><p>Le chauffeur envoie son dossier. TACLAR valide les documents, confirme la caution, puis active le chauffeur.</p><div class="field-grid"><div><label>Nom et prénom chauffeur</label><input id="signupName" placeholder="Ex : Serge Ndong"></div><div><label>Téléphone chauffeur</label><input id="signupPhone" placeholder="Ex : +241 77 45 90 12"></div><div><label>Véhicule</label><input id="signupVehicle" placeholder="Ex : Toyota Noah"></div><div><label>Plaque</label><input id="signupPlate" placeholder="Ex : GA-421-LB"></div><div><label>Axe souhaité</label><select id="signupAxis"></select></div><div><label>Prix transport / place</label><input id="signupPrice" disabled></div><div><label>Nombre de places</label><input id="signupSeats" type="number" min="1" step="1" placeholder="Ex : 6"></div><div><label>Dépôt garantie calculé</label><input id="signupDeposit" value="0 FCFA" disabled></div><div><label>Permis de conduire</label><input id="signupLicense" type="file"></div><div><label>Pièce d'identité</label><input id="signupIdCard" type="file"></div></div><div class="notice warning"><strong>Étape 1 :</strong> soumettre le dossier chauffeur. Les fichiers sont simulés par leur nom dans cette démo.</div><div class="actions"><button id="submitDriver">Soumettre le dossier chauffeur</button><button class="secondary" id="clearDriver">Vider le formulaire</button></div><div id="signupMsg" class="notice hidden"></div></div><div class="card"><h2>Validation TACLAR</h2><p>TACLAR voit ici les dossiers reçus et valide les étapes.</p><div id="applicationsList" class="list"></div></div></div>`);fillAxisSelect($('signupAxis'));$('signupAxis').onchange=()=>{const axis=$('signupAxis').value;$('signupPrice').value=axis?money(axisPrices[axis]):''};$('signupSeats').oninput=()=>{$('signupDeposit').value=money(Math.max(0,Number($('signupSeats').value||0))*taclarFee)};$('submitDriver').onclick=submitDriver;$('clearDriver').onclick=()=>renderNewDriver();renderApplicationsList()}
async function submitDriver(){const name=$('signupName').value.trim(),phone=$('signupPhone').value.trim(),vehicle=$('signupVehicle').value.trim(),plate=$('signupPlate').value.trim(),axis=$('signupAxis').value,seats=Number($('signupSeats').value||0);if(!name||!phone||!vehicle||!plate||!axis||seats<1){alert('Remplissez nom, téléphone, véhicule, plaque, axe et nombre de places.');return}await addDoc({type:'driverApplication',name,phone,vehicle,plate,axis,seats,price:axisPrices[axis]||0,deposit:seats*taclarFee,licenseName:$('signupLicense').files[0]?.name||'Non joint',idCardName:$('signupIdCard').files[0]?.name||'Non joint',status:'submitted',docsValidated:false,depositPaid:false,depositValidated:false,active:false});$('signupMsg').className='notice success';$('signupMsg').textContent='Dossier envoyé à TACLAR.';['signupName','signupPhone','signupVehicle','signupPlate','signupSeats','signupLicense','signupIdCard'].forEach(id=>$(id).value='');$('signupAxis').value='';$('signupPrice').value='';$('signupDeposit').value='0 FCFA'}
function renderApplicationsList(){const box=$('applicationsList');if(!box)return;const list=apps();if(!list.length){box.innerHTML='<div class="notice">Aucun dossier chauffeur reçu pour le moment.</div>';return}box.innerHTML=list.map(a=>`<div class="item"><div class="item-top"><div><div class="name">${a.name}</div><div class="axis-name">${a.axis}</div><div>${a.vehicle} - ${a.plate}</div></div><span class="badge ${a.active?'ok':'warn'}">${a.active?'Chauffeur actif':statusText(a.status)}</span></div><div class="facts"><div class="fact"><small>Téléphone</small><strong>${a.phone}</strong></div><div class="fact"><small>Places</small><strong>${a.seats}</strong></div><div class="fact"><small>Prix axe</small><strong>${money(a.price)}</strong></div><div class="fact"><small>Caution</small><strong>${money(a.deposit)}</strong></div><div class="fact"><small>Permis</small><strong>${a.licenseName||'-'}</strong></div><div class="fact"><small>Identité</small><strong>${a.idCardName||'-'}</strong></div></div><div class="actions"><button onclick="updateDoc('${a.id}',{status:'docs_validated',docsValidated:true})" ${a.docsValidated?'disabled':''}>Valider documents</button><button class="orange" onclick="updateDoc('${a.id}',{status:'deposit_paid',depositPaid:true})" ${!a.docsValidated||a.depositPaid?'disabled':''}>Marquer caution déposée</button><button onclick="updateDoc('${a.id}',{status:'deposit_validated',depositValidated:true})" ${!a.depositPaid||a.depositValidated?'disabled':''}>Valider caution reçue</button><button class="blue" onclick="updateDoc('${a.id}',{status:'active',active:true})" ${!a.depositValidated||a.active?'disabled':''}>Activer chauffeur</button></div></div>`).join('')}
function renderPublish(){setShell('publish',`<div class="grid two"><div class="card"><h2>Publier un trajet</h2><p>Seuls les chauffeurs actifs peuvent publier une disponibilité.</p><div class="field-grid"><div><label>Chauffeur validé</label><select id="publishDriver"></select></div><div><label>Axe</label><input id="publishAxis" disabled></div><div><label>Véhicule</label><input id="publishVehicle" disabled></div><div><label>Plaque</label><input id="publishPlate" disabled></div><div><label>Places disponibles</label><input id="publishSeats" type="number" min="1"></div><div><label>Prix transport / place</label><input id="publishPrice" disabled></div><div><label>Date de départ</label><input id="publishDay" type="date"></div><div><label>Heure d'enregistrement</label><select id="publishCheckin"></select></div><div><label>Heure de départ</label><select id="publishTime"></select></div><div><label>Point d'embarquement</label><input id="publishBoarding" placeholder="Ex : Gare routière"></div></div><div class="actions"><button id="publishBtn">Publier le trajet</button></div><div id="publishMsg" class="notice hidden"></div></div><div class="card"><h2>Règle</h2><div class="notice success">Un chauffeur peut publier seulement si son dossier et sa caution sont validés.</div><div id="activeDriversBox" class="list"></div></div></div>`);const drivers=activeApps();$('publishDriver').innerHTML='<option value="">-- Choisir chauffeur --</option>'+drivers.map(d=>`<option value="${d.id}">${d.name}</option>`).join('');fillTimeSelect($('publishCheckin'),'-- Heure enregistrement --');fillTimeSelect($('publishTime'),'-- Heure départ --');$('publishDriver').onchange=syncPublishDriver;$('publishBtn').onclick=publishOffer;renderActiveDrivers();syncPublishDriver()}
function syncPublishDriver(){const a=activeApps().find(x=>x.id===$('publishDriver').value);['publishAxis','publishVehicle','publishPlate','publishPrice','publishSeats'].forEach(id=>$(id).value='');if(!a)return;$('publishAxis').value=a.axis;$('publishVehicle').value=a.vehicle;$('publishPlate').value=a.plate;$('publishPrice').value=money(a.price);$('publishSeats').value=a.seats}
async function publishOffer(){const a=activeApps().find(x=>x.id===$('publishDriver').value);if(!a){alert('Choisissez un chauffeur validé.');return}const day=$('publishDay').value,checkinTime=$('publishCheckin').value,time=$('publishTime').value,boarding=$('publishBoarding').value.trim(),seats=Number($('publishSeats').value||0);if(!day||!checkinTime||!time||!boarding||seats<1){alert('Complétez date, heures, embarquement et places.');return}await addDoc({type:'offer',driverAppId:a.id,driver:a.name,phone:a.phone,vehicle:a.vehicle,plate:a.plate,axis:a.axis,seats,booked:0,price:a.price,day,checkinTime,time,boarding,status:'Disponible',source:'v29'});$('publishMsg').className='notice success';$('publishMsg').textContent='Trajet publié. Il apparaît maintenant côté client et booking.';$('publishDay').value='';$('publishCheckin').value='';$('publishTime').value='';$('publishBoarding').value=''}
function renderActiveDrivers(){const box=$('activeDriversBox');if(!box)return;const list=activeApps();box.innerHTML=list.length?list.map(a=>`<div class="item"><strong>${a.name}</strong><br>${a.axis}<br>${a.vehicle} - ${a.plate}</div>`).join(''):'<div class="notice">Aucun chauffeur actif pour le moment.</div>'}
function renderBooking(){const all=offers();const pending=requests().filter(r=>r.status==='pending').length;const paid=requests().filter(r=>r.status==='paid').reduce((s,r)=>s+Number(r.seats||1),0);setShell('booking',`<div class="card"><h2>Booking / Disponibilités chauffeur</h2><p>Les demandes à traiter remontent ici. Le chauffeur confirme ou refuse.</p><div class="kpi"><div><b>${all.length}</b><span>trajets</span></div><div><b>${pending}</b><span>demandes</span></div><div><b>${paid}</b><span>places payées</span></div><div><b>${money(paid*taclarFee)}</b><span>TACLAR</span></div></div><div id="bookingList" class="list"></div></div>`);const box=$('bookingList');if(!all.length){box.innerHTML='<div class="notice">Aucun trajet publié.</div>';return}const sorted=[...all].sort((a,b)=>{const ap=reqsForOffer(a.id).some(r=>r.status==='pending')?1:0;const bp=reqsForOffer(b.id).some(r=>r.status==='pending')?1:0;return bp-ap||(b.createdAt||0)-(a.createdAt||0)});box.innerHTML=sorted.map(renderBookingOffer).join('')}
function renderBookingOffer(o){const reqs=reqsForOffer(o.id).filter(r=>r.status!=='deleted');const passengerCount=reqs.filter(r=>['confirmed','paid'].includes(r.status)).reduce((s,r)=>s+Number(r.seats||1),0);const revenue=paidSeats(o)*Number(o.price||0);return `<div class="item selected"><div class="item-top"><div><div class="name">${o.driver}</div><div class="axis-name">${o.axis}</div></div><span class="badge ${freeSeats(o)<=0?'full':'ok'}">${freeSeats(o)<=0?'Complet':freeSeats(o)+' place(s) libres'}</span></div><div class="facts"><div class="fact"><small>Jour</small><strong>${o.day}</strong></div><div class="fact"><small>Enregistrement</small><strong>${o.checkinTime}</strong></div><div class="fact"><small>Départ</small><strong>${o.time}</strong></div><div class="fact"><small>Véhicule</small><strong>${o.vehicle}</strong></div><div class="fact"><small>Plaque</small><strong>${o.plate}</strong></div><div class="fact"><small>Prix / place</small><strong>${money(o.price)}</strong></div><div class="fact"><small>Nombre passagers confirmés</small><strong>${passengerCount}</strong></div><div class="fact"><small>Recette chauffeur payée</small><strong>${money(revenue)}</strong></div><div class="fact"><small>Embarquement</small><strong>${o.boarding}</strong></div><div class="fact"><small>Caution versée à TACLAR</small><strong>OK</strong></div></div><div class="list" style="margin-top:12px">${reqs.length?reqs.map(r=>renderBookingRequest(r,o)).join(''):'<div class="notice">Aucune demande pour ce trajet.</div>'}</div></div>`}
function renderBookingRequest(r,o){const passengerList=(r.passengerNames||[r.clientName]).join(', ');return `<div class="item"><div class="item-top"><div><strong>${r.groupLeader||r.clientName}</strong><div class="muted">${r.clientPhone} · ${r.seats} place(s) · ${r.requestCode||''} · ${r.createdLabel||''}</div><div>${passengerList}</div></div><span class="badge ${r.status==='paid'?'ok':r.status==='pending'?'warn':'full'}">${statusText(r.status)}</span></div>${r.status==='paid'?`<div class="notice success">Commission TACLAR payée. Rendez-vous le ${o.day} à ${o.checkinTime} au point d'embarquement : ${o.boarding}. Départ prévu : ${o.time}.</div>`:''}<div class="actions"><button onclick="updateDoc('${r.id}',{status:'confirmed'})" ${r.status!=='pending'?'disabled':''}>Confirmer place</button><button class="ghost" onclick="updateDoc('${r.id}',{status:'refused'})" ${r.status!=='pending'?'disabled':''}>Refuser</button><button class="red" onclick="deleteDocHard('${r.id}')" ${r.status==='paid'?'disabled':''}>Supprimer erreur</button></div></div>`}
function renderClient(){setShell('client',`<div class="grid two"><div class="card"><h2>Client - chercher un trajet</h2><p>Le client choisit un axe, sélectionne un chauffeur et demande une ou plusieurs places.</p><div class="field-grid"><div><label>Axe recherché</label><select id="clientAxis"></select></div><div><label>Mode de paiement TACLAR</label><select id="paymentMode"><option value="single">Individuel - une place</option><option value="group">Groupe/famille - plusieurs places</option></select></div><div><label>Nom du client / responsable</label><input id="clientName" placeholder="Ex : Arielle Mba"></div><div><label>Téléphone responsable</label><input id="clientPhone" placeholder="Ex : +241 66 12 34 56"></div><div id="groupSeatsWrap" class="hidden"><label>Nombre de places à réserver</label><input id="groupSeats" type="number" min="2" max="6" value="2"></div></div><div id="groupNamesWrap" class="hidden"><label>Noms des passagers du groupe</label><div id="groupNames"></div></div><div id="clientOffers" class="list" style="margin-top:12px"></div></div><div class="card"><h2>Suivi client</h2><div class="notice"><div class="row"><span>Frais TACLAR</span><strong>${money(taclarFee)} / place</strong></div><div class="row"><span>Transport</span><strong>Payé au chauffeur</strong></div><div class="row"><span>Infos complètes</span><strong>Après paiement TACLAR</strong></div></div><div id="toPayBox" class="list"></div><h3 style="margin-top:14px">Mes réservations payées</h3><div id="paidBox" class="list"></div></div></div>`);fillAxisSelect($('clientAxis'));$('clientAxis').onchange=renderClientOffers;$('paymentMode').onchange=()=>{syncGroupFields();renderClientOffers()};$('groupSeats').oninput=renderGroupNameInputs;syncGroupFields();renderClientOffers();renderPayments()}
function syncGroupFields(){const group=$('paymentMode').value==='group';$('groupSeatsWrap').classList.toggle('hidden',!group);$('groupNamesWrap').classList.toggle('hidden',!group);if(group)renderGroupNameInputs()}
function renderGroupNameInputs(){const count=Math.max(2,Number($('groupSeats').value||2));$('groupSeats').value=count;const existing=[...document.querySelectorAll('.groupName')].map(i=>i.value);$('groupNames').innerHTML=Array.from({length:count},(_,i)=>`<input class="groupName" placeholder="Nom passager ${i+1}" value="${existing[i]||''}" style="margin-bottom:8px">`).join('')}
function renderClientOffers(){const axis=$('clientAxis').value,box=$('clientOffers');if(!axis){box.innerHTML='<div class="notice">Choisissez un axe pour afficher les chauffeurs disponibles.</div>';return}const list=offers().filter(o=>o.axis===axis&&o.status==='Disponible').sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));if(!list.length){box.innerHTML='<div class="notice warning">Aucun trajet disponible pour cet axe.</div>';return}box.innerHTML=list.map(o=>{const selected=selectedOfferId===o.id;const free=freeSeats(o);return `<div class="item ${selected?'selected':''}"><div class="item-top"><div><div class="name">${o.driver}</div><div class="axis-name">${o.axis}</div></div><span class="badge ${free<=0?'full':'ok'}">${free<=0?'Complet':free+' place(s)'}</span></div>${selected?`<div class="facts"><div class="fact"><small>Date</small><strong>${o.day}</strong></div><div class="fact"><small>Enregistrement</small><strong>${o.checkinTime}</strong></div><div class="fact"><small>Départ</small><strong>${o.time}</strong></div><div class="fact"><small>Voiture</small><strong>${o.vehicle}</strong></div><div class="fact"><small>Prix / place</small><strong>${money(o.price)}</strong></div></div><div class="notice"><strong>Avant paiement TACLAR :</strong> téléphone masqué (${phoneMask(o.phone)}), point d'embarquement général : ${o.boarding}.</div>`:`<div class="notice">Cliquez sur Voir les détails pour afficher le jour, l'heure, le véhicule, le prix et le point d'embarquement.</div>`}<div class="actions"><button class="ghost" onclick="selectedOfferId='${selected?'':o.id}';renderClientOffers()">${selected?'Masquer les détails':'Voir les détails'}</button><button onclick="requestPlaces('${o.id}')" ${free<=0?'disabled':''}>${$('paymentMode').value==='group'?'Demander les places':'Demander une place'}</button></div></div>`}).join('')}
async function requestPlaces(offerId){const o=offers().find(x=>x.id===offerId);const mode=$('paymentMode').value,name=$('clientName').value.trim(),phone=$('clientPhone').value.trim();if(!name||!phone){alert('Remplissez le nom du responsable et son téléphone.');return}let passengerNames=[name],seats=1;if(mode==='group'){seats=Math.max(2,Number($('groupSeats').value||2));passengerNames=[...document.querySelectorAll('.groupName')].map(i=>i.value.trim()).filter(Boolean);if(passengerNames.length!==seats){alert('Remplissez les noms des '+seats+' passagers du groupe.');return}}if(seats>freeSeats(o)){alert('Il ne reste pas assez de places dans ce véhicule.');return}await addDoc({type:'request',offerId:o.id,clientName:name,clientPhone:phone,groupLeader:name,paymentMode:mode,seats,passengerNames,status:'pending',requestCode:'REQ-'+Math.floor(1000+Math.random()*9000),createdLabel:nowLabel()});alert('Demande envoyée au chauffeur pour confirmation.');$('clientName').value='';$('clientPhone').value='';if(mode==='group')renderGroupNameInputs()}
function renderPayments(){const toPay=requests().filter(r=>r.status==='confirmed');$('toPayBox').innerHTML=toPay.length?toPay.map(r=>{const o=offers().find(x=>x.id===r.offerId)||{};return `<div class="item"><strong>${r.groupLeader||r.clientName}</strong><div>${r.seats} place(s) confirmée(s) avec ${o.driver||'-'}</div><div class="row"><span>Total frais TACLAR</span><strong>${money(Number(r.seats||1)*taclarFee)}</strong></div><button class="orange" onclick="updateDoc('${r.id}',{status:'paid',paidAt:Date.now()})">Payer commission TACLAR</button></div>`}).join(''):'<div class="notice">Aucune place confirmée en attente de paiement.</div>';const paid=requests().filter(r=>r.status==='paid').sort((a,b)=>(b.paidAt||0)-(a.paidAt||0));$('paidBox').innerHTML=paid.length?paid.map(r=>{const o=offers().find(x=>x.id===r.offerId)||{};return `<div class="item"><strong>Reçu ${r.paymentMode==='group'?'groupe':'individuel'}</strong><div class="row"><span>Responsable</span><strong>${r.groupLeader||r.clientName}</strong></div><div class="row"><span>Passagers</span><strong>${(r.passengerNames||[]).join(', ')}</strong></div><div class="row"><span>Axe</span><strong>${o.axis||'-'}</strong></div><div class="row"><span>Chauffeur</span><strong>${o.driver||'-'}</strong></div><div class="row"><span>Téléphone chauffeur</span><strong>${o.phone||'-'}</strong></div><div class="row"><span>Enregistrement</span><strong>${o.checkinTime||'-'}</strong></div><div class="row"><span>Départ</span><strong>${o.time||'-'}</strong></div><div class="row"><span>Embarquement</span><strong>${o.boarding||'-'}</strong></div><div class="row"><span>Total frais TACLAR</span><strong>${money(Number(r.seats||1)*taclarFee)}</strong></div><button class="blue" onclick="window.print()">Télécharger / imprimer le reçu</button></div>`}).join(''):'<div class="notice">Les informations complètes du chauffeur apparaissent ici après paiement.</div>'}

document.addEventListener('DOMContentLoaded',initFirebase);
