
const taclarFee=2000;
const collectionName='taclar_interurbain';
const axes=['Libreville → Oyem → Bitam','Libreville → Lambaréné','Libreville → Mitzic'];
const axisPrices={'Libreville → Oyem → Bitam':25000,'Libreville → Lambaréné':18000,'Libreville → Mitzic':22000};
const departureTimes=['05h00','05h30','06h00','06h30','07h00','07h30','08h00','08h30','09h00','09h30','10h00','10h30','12h00','14h00','15h00','16h00','18h00'];
const taclarWhatsApp='241000000000';
let db=null,docs=[],ready=false,selectedOfferId=null;
function $(id){return document.getElementById(id)}
function money(n){return Number(n||0).toLocaleString('fr-FR')+' FCFA'}
function nowLabel(){return new Date().toLocaleString('fr-FR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'})}
function makeDriverCode(){return 'CH-'+Math.floor(10000+Math.random()*90000)}
function makePin(){return String(Math.floor(1000+Math.random()*9000))}
function getDriverSession(){try{return JSON.parse(localStorage.getItem('taclar_driver_session')||'null')}catch{return null}}
function setDriverSession(id,pin,allowActive=false){localStorage.setItem('taclar_driver_session',JSON.stringify({id,pin,allowActive}))}
function clearDriverSession(){localStorage.removeItem('taclar_driver_session')}
function byType(t){return docs.filter(d=>d.type===t).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))}
function apps(){return byType('driverApplication')}
function activeApps(){return apps().filter(a=>a.active)}
function offers(){return byType('offer')}
function requests(){return byType('request')}
function reqsForOffer(id){return requests().filter(r=>r.offerId===id)}
function liveReqsForOffer(id){return reqsForOffer(id).filter(r=>!['refused','deleted'].includes(r.status))}
function paidReqsForOffer(id){return reqsForOffer(id).filter(r=>r.status==='paid')}
function seatsTaken(offer){return liveReqsForOffer(offer.id).reduce((s,r)=>s+Number(r.seats||1),0)}
function paidSeats(offer){return paidReqsForOffer(offer.id).reduce((s,r)=>s+Number(r.seats||1),0)}
function freeSeats(offer){return Math.max(0,Number(offer.seats||0)-Number(offer.booked||0)-seatsTaken(offer))}
function phoneMask(p){p=String(p||'');return p.length>5?p.slice(0,7)+' ** ** '+p.slice(-2):'masqué'}
function whatsappLink(phone,text){const digits=String(phone||'').replace(/\D/g,'');return `https://wa.me/${digits||taclarWhatsApp}?text=${encodeURIComponent(text)}`}
function statusText(s){return {submitted:'Documents en cours de traitement',docs_validated:'Documents approuvés - caution à déposer',deposit_paid:'Caution déposée - vérification TACLAR',deposit_validated:'Caution reçue - autorisation en attente',active:'Autorisé à publier',pending:'Demande envoyée',confirmed:'Confirmée chauffeur - frais TACLAR à payer',paid:'Commission TACLAR payée',refused:'Refusée',deleted:'Supprimée'}[s]||s||'-'}
function fillAxisSelect(sel,empty='-- Choisir un axe --'){if(!sel)return;const v=sel.value;sel.innerHTML=`<option value="">${empty}</option>`+axes.map(a=>`<option value="${a}">${a}</option>`).join('');if(axes.includes(v))sel.value=v}
function fillTimeSelect(sel,empty='-- Choisir --'){if(!sel)return;const v=sel.value;sel.innerHTML=`<option value="">${empty}</option>`+departureTimes.map(t=>`<option value="${t}">${t}</option>`).join('');if(departureTimes.includes(v))sel.value=v}
async function addDoc(data){if(!db)throw new Error('Firebase non connecté');return db.collection(collectionName).add({...data,createdAt:Date.now(),updatedAt:Date.now()})}
async function updateDoc(id,data){if(!db)throw new Error('Firebase non connecté');return db.collection(collectionName).doc(id).set({...data,updatedAt:Date.now()},{merge:true})}
async function deleteDocHard(id){if(!db)throw new Error('Firebase non connecté');return db.collection(collectionName).doc(id).delete()}
async function resetTestData(){
  if(!db)throw new Error('Firebase non connecté');
  if(!confirm('Réinitialiser la base de test TACLAR Interurbain ? Tous les chauffeurs, trajets et demandes de test seront supprimés.'))return;
  const snap=await db.collection(collectionName).get();
  const batch=db.batch();
  snap.docs.forEach(doc=>batch.delete(doc.ref));
  await batch.commit();
  clearDriverSession();
  selectedOfferId=null;
  alert('Base de test réinitialisée. Tu peux créer un vrai chauffeur et un vrai client.');
}
function initFirebase(){const cfg=window.TACLAR_FIREBASE_CONFIG;if(!cfg||String(cfg.apiKey||'').includes('COLLER_')){showLoad('Firebase non configuré');return}firebase.initializeApp(cfg);db=firebase.firestore();showLoad('Connexion Firebase...');db.collection(collectionName).onSnapshot(snap=>{docs=snap.docs.map(d=>({id:d.id,...d.data()}));ready=true;showLoad('Synchronisé');setTimeout(()=>showLoad(''),900);renderPage();},err=>{showLoad('Erreur Firebase: '+err.message)})}
function showLoad(txt){let el=$('syncStatus');if(!el){el=document.createElement('div');el.id='syncStatus';el.className='loading';document.body.appendChild(el)}el.textContent=txt;el.style.display=txt?'block':'none'}
function header(active){
  const pageTitles={
    new:'Espace chauffeur',
    validation:'Validation TACLAR',
    publish:'Publier un trajet',
    booking:'Booking / Disponibilités chauffeur',
    client:'Espace client',
    portal:'Mise en relation client-chauffeur'
  };
  return `<header class="hero"><div class="hero-inner"><div class="brand"><div class="logo">TACLAR</div><div><h1>${pageTitles[active]||'TACLAR Interurbain'}</h1></div></div></div></header>`
}
function setShell(active,main){$('app').innerHTML=header(active)+main}
function renderPage(){const page=document.body.dataset.page;if(page==='new')renderNewDriver();else if(page==='validation')renderValidation();else if(page==='publish')renderPublish();else if(page==='booking')renderBooking();else if(page==='client')renderClient();else renderPortal()}
function renderPortal(){setShell('portal',`<div class="card"><h2>Accès TACLAR Interurbain</h2><p>Chaque rôle dispose maintenant de sa propre page.</p><div class="portal-grid"><a href="taclar_nouveau_chauffeur.html"><strong>Espace chauffeur</strong><p>Inscription, connexion par PIN et suivi personnel du dossier.</p></a><a href="taclar_validation.html"><strong>Validation TACLAR</strong><p>Validation interne des documents, de la caution et de l'autorisation.</p></a><a href="taclar_publier_trajet.html"><strong>Publier trajet</strong><p>Un chauffeur autorisé publie une disponibilité.</p></a><a href="taclar_booking.html"><strong>Booking / Disponibilités</strong><p>Le chauffeur traite les demandes clients.</p></a><a href="taclar_client.html"><strong>Client</strong><p>Le client cherche un axe et réserve une ou plusieurs places.</p></a></div></div>`)}
function renderNewDriver(){
  const session=getDriverSession();
  const current=session?apps().find(a=>a.id===session.id&&String(a.pin||'')===String(session.pin||'')):null;
  if(current&&current.active&&current.mustRelogin&&!session.allowActive){clearDriverSession();renderNewDriver();return}
  if(current){renderDriverDashboard(current);return}
  if(session)clearDriverSession();
  setShell('new',`<div class="grid two"><div class="card"><h2>Nouveau chauffeur - rejoindre TACLAR</h2><p>Crée ton dossier une seule fois. Tu recevras ensuite un numéro de dossier et un code PIN pour suivre son traitement.</p><div class="field-grid"><div><label>Nom et prénom chauffeur</label><input id="signupName" placeholder="Ex : Serge Ndong"></div><div><label>Téléphone chauffeur</label><input id="signupPhone" placeholder="Ex : +241 77 45 90 12"></div><div><label>Véhicule</label><input id="signupVehicle" placeholder="Ex : Toyota Noah"></div><div><label>Plaque</label><input id="signupPlate" placeholder="Ex : GA-421-LB"></div><div><label>Axe souhaité</label><select id="signupAxis"></select></div><div><label>Prix transport / place</label><input id="signupPrice" disabled></div><div><label>Nombre de places</label><input id="signupSeats" type="number" min="1" step="1" placeholder="Ex : 6"></div><div><label>Dépôt garantie calculé</label><input id="signupDeposit" value="0 FCFA" disabled></div><div><label>Permis de conduire</label><input id="signupLicense" type="file"></div><div><label>Pièce d'identité</label><input id="signupIdCard" type="file"></div></div><div class="notice warning"><strong>Étape 1 :</strong> soumettre le dossier chauffeur. Les fichiers sont simulés par leur nom dans cette démo.</div><div class="actions"><button id="submitDriver">Soumettre le dossier chauffeur</button><button class="secondary" id="clearDriver">Vider le formulaire</button></div></div><div class="card"><h2>Déjà inscrit ?</h2><p>Entre ton numéro de dossier et ton code PIN pour consulter uniquement ton propre dossier.</p><div><label>Numéro de dossier</label><input id="loginDriverCode" placeholder="Ex : CH-12345"></div><div style="margin-top:12px"><label>Code PIN</label><input id="loginDriverPin" inputmode="numeric" maxlength="4" placeholder="4 chiffres"></div><div class="actions"><button id="loginDriver">Ouvrir mon dossier</button><button class="ghost" id="forgotDriverCode">Code oublié ?</button></div><div id="loginMsg" class="notice danger hidden"></div></div></div>`);
  fillAxisSelect($('signupAxis'));
  $('signupAxis').onchange=()=>{const axis=$('signupAxis').value;$('signupPrice').value=axis?money(axisPrices[axis]):''};
  $('signupSeats').oninput=()=>{$('signupDeposit').value=money(Math.max(0,Number($('signupSeats').value||0))*taclarFee)};
  $('submitDriver').onclick=submitDriver;
  $('clearDriver').onclick=()=>renderNewDriver();
  $('loginDriver').onclick=loginDriver;
  $('forgotDriverCode').onclick=forgotDriverCode;
}
async function submitDriver(){
  const name=$('signupName').value.trim(),phone=$('signupPhone').value.trim(),vehicle=$('signupVehicle').value.trim(),plate=$('signupPlate').value.trim(),axis=$('signupAxis').value,seats=Number($('signupSeats').value||0);
  if(!name||!phone||!vehicle||!plate||!axis||seats<1){alert('Remplis le nom, le téléphone, le véhicule, la plaque, l’axe et le nombre de places.');return}
  const driverCode=makeDriverCode(),pin=makePin();
  const ref=await addDoc({type:'driverApplication',driverCode,pin,name,phone,vehicle,plate,axis,seats,price:axisPrices[axis]||0,deposit:seats*taclarFee,licenseName:$('signupLicense').files[0]?.name||'Non joint',idCardName:$('signupIdCard').files[0]?.name||'Non joint',status:'submitted',docsValidated:false,depositPaid:false,depositValidated:false,active:false});
  setDriverSession(ref.id,pin,false);
  alert(`Dossier envoyé.\nNuméro : ${driverCode}\nCode PIN : ${pin}\nNote-les pour retrouver ton dossier.`);
  renderPage();
}
function loginDriver(){
  const code=$('loginDriverCode').value.trim().toUpperCase(),pin=$('loginDriverPin').value.trim();
  const app=apps().find(a=>String(a.driverCode||'').toUpperCase()===code&&String(a.pin||'')===pin);
  if(!app){$('loginMsg').classList.remove('hidden');$('loginMsg').textContent='Numéro de dossier ou code PIN incorrect.';return}
  setDriverSession(app.id,pin,true);
  renderPage();
}
function forgotDriverCode(){
  const msg='Bonjour TACLAR, j’ai oublié mon numéro de dossier ou mon code PIN chauffeur. Merci de me le renvoyer. Nom : ... Téléphone : ...';
  window.open(whatsappLink(taclarWhatsApp,msg),'_blank');
}
function renderDriverDashboard(a){
  const steps=[{done:true,label:'Dossier envoyé'},{done:!!a.docsValidated,label:'Documents approuvés'},{done:!!a.depositPaid,label:'Caution déposée'},{done:!!a.depositValidated,label:'Caution reçue'},{done:!!a.active,label:'Autorisé à publier'}];
  let message='Tes documents ont été reçus et sont en cours de traitement.';
  if(a.docsValidated&&!a.depositPaid)message=`Tes documents sont approuvés. Dépose maintenant la caution de ${money(a.deposit)}.`;
  else if(a.depositPaid&&!a.depositValidated)message='Ta caution est déclarée payée. TACLAR vérifie maintenant sa réception.';
  else if(a.depositValidated&&!a.active)message='Ta caution est reçue. TACLAR doit encore autoriser la publication.';
  else if(a.active)message='Ton dossier est complet. Tu peux publier un trajet depuis ton espace chauffeur.';
  setShell('new',`<div class="card driver-space"><div class="item-top"><div><h2>Suivi de mon dossier chauffeur</h2><p class="muted">Bienvenue, <strong>${a.name}</strong>.</p></div><span class="badge ${a.active?'ok':'warn'}">${statusText(a.status)}</span></div><div class="credentials"><div><small>Numéro de dossier</small><strong>${a.driverCode||'Ancien dossier'}</strong></div><div><small>Code PIN personnel</small><strong>${a.pin||'Non défini'}</strong></div></div><div class="notice warning"><strong>À conserver :</strong> note ton numéro de dossier et ton code PIN pour te reconnecter depuis un autre téléphone.</div><div class="timeline">${steps.map(s=>`<div class="${s.done?'done':''}"><span>${s.done?'✓':'○'}</span><strong>${s.label}</strong></div>`).join('')}</div><div class="notice ${a.active?'success':''}">${message}</div><div class="facts"><div class="fact"><small>Nom</small><strong>${a.name}</strong></div><div class="fact"><small>Téléphone</small><strong>${a.phone}</strong></div><div class="fact"><small>Véhicule</small><strong>${a.vehicle}</strong></div><div class="fact"><small>Plaque</small><strong>${a.plate}</strong></div><div class="fact"><small>Axe souhaité</small><strong>${a.axis}</strong></div><div class="fact"><small>Places déclarées</small><strong>${a.seats}</strong></div><div class="fact"><small>Caution</small><strong>${money(a.deposit)}</strong></div><div class="fact"><small>Statut</small><strong>${statusText(a.status)}</strong></div></div>${a.docsValidated&&!a.depositPaid?`<div class="actions"><button class="orange" onclick="driverPayDeposit('${a.id}')">Déposer la caution</button></div>`:''}${a.active?driverPublishPanel(a)+driverRequestsPanel(a):''}<div class="actions driver-logout"><button class="secondary" onclick="logoutDriver()">Se déconnecter</button></div></div>`);
  if(a.active){fillTimeSelect($('driverPublishCheckin'),'-- Heure enregistrement --');fillTimeSelect($('driverPublishTime'),'-- Heure départ --')}
}
function driverPublishPanel(a){
  return `<section class="driver-publish-panel"><h2>Publier mon trajet</h2><p>Complète uniquement les informations de départ. Les informations chauffeur sont déjà reprises depuis ton dossier validé.</p><div class="field-grid"><div><label>Axe</label><input value="${a.axis}" disabled></div><div><label>Véhicule</label><input value="${a.vehicle}" disabled></div><div><label>Plaque</label><input value="${a.plate}" disabled></div><div><label>Prix transport / place</label><input value="${money(a.price)}" disabled></div><div><label>Places disponibles</label><input id="driverPublishSeats" type="number" min="1" max="${a.seats}" value="${a.seats}"></div><div><label>Date de départ</label><input id="driverPublishDay" type="date"></div><div><label>Heure d'enregistrement</label><select id="driverPublishCheckin"></select></div><div><label>Heure de départ</label><select id="driverPublishTime"></select></div><div class="full"><label>Point d'embarquement</label><input id="driverPublishBoarding" placeholder="Ex : Gare routière"></div></div><div class="actions"><button onclick="publishDriverTrip('${a.id}')">Publier le trajet</button></div><div id="driverPublishMsg" class="notice hidden"></div></section>`
}
function driverRequestsPanel(a){
  const myOffers=offers().filter(o=>o.driverAppId===a.id);
  const myRequests=requests().filter(r=>myOffers.some(o=>o.id===r.offerId)&&r.status!=='deleted').sort((x,y)=>{const score=r=>r.status==='pending'?3:r.status==='confirmed'?2:r.status==='paid'?1:0;return score(y)-score(x)||(y.createdAt||0)-(x.createdAt||0)});
  return `<section class="driver-requests-panel"><h2>Demandes reçues</h2>${myOffers.length?`<p class="muted">${myOffers.length} disponibilité(s) publiée(s). Les demandes clients arrivent ici, dans ton espace chauffeur.</p>`:'<div class="notice">Aucune disponibilité publiée pour le moment.</div>'}<div class="list">${myRequests.length?myRequests.map(r=>{const o=myOffers.find(x=>x.id===r.offerId)||{};return renderDriverRequest(r,o)}).join(''):'<div class="notice">Aucune demande client à traiter.</div>'}</div></section>`
}
function renderDriverRequest(r,o){
  const passengerList=(r.passengerNames||[r.clientName]).join(', ');
  const reasonId='driver-reason-'+r.id;
  return `<div class="item"><div class="item-top"><div><strong>${r.groupLeader||r.clientName}</strong><div class="muted">${o.axis||'-'} · ${r.seats} place(s) · ${r.requestCode||''}</div><div>${passengerList}</div></div><span class="badge ${r.status==='paid'?'ok':r.status==='pending'?'warn':r.status==='refused'?'full':'warn'}">${statusText(r.status)}</span></div>${r.status==='paid'?`<div class="notice success">Commission TACLAR payée. Rendez-vous le ${o.day||'-'} à ${o.checkinTime||'-'} au point d'embarquement : ${o.boarding||'-'}. Départ prévu : ${o.time||'-'}.</div>`:''}${r.status==='refused'?`<div class="notice danger">Demande refusée. Motif : ${r.refusalReason||'Non précisé'}.</div>`:''}<div class="actions"><button onclick="updateDoc('${r.id}',{status:'confirmed',confirmedAt:Date.now()})" ${r.status!=='pending'?'disabled':''}>Confirmer place</button><select id="${reasonId}" ${r.status!=='pending'?'disabled':''}><option value="Véhicule déjà complet">Véhicule déjà complet</option><option value="Départ annulé">Départ annulé</option><option value="Horaire modifié">Horaire modifié</option><option value="Client à rappeler">Client à rappeler</option><option value="Autre motif">Autre motif</option></select><button class="ghost" onclick="refuseRequest('${r.id}','${reasonId}')" ${r.status!=='pending'?'disabled':''}>Refuser</button></div></div>`
}
async function publishDriverTrip(appId){
  const a=apps().find(x=>x.id===appId&&x.active);
  if(!a){alert('Dossier chauffeur non autorisé à publier.');return}
  const day=$('driverPublishDay').value,checkinTime=$('driverPublishCheckin').value,time=$('driverPublishTime').value,boarding=$('driverPublishBoarding').value.trim(),seats=Number($('driverPublishSeats').value||0);
  if(!day||!checkinTime||!time||!boarding||seats<1){alert('Complète date, heures, point d’embarquement et places.');return}
  await addDoc({type:'offer',driverAppId:a.id,driver:a.name,phone:a.phone,vehicle:a.vehicle,plate:a.plate,axis:a.axis,seats,booked:0,price:a.price,day,checkinTime,time,boarding,status:'Disponible',source:'driver-space'});
  $('driverPublishMsg').className='notice success';
  $('driverPublishMsg').textContent='Trajet publié. Il apparaît maintenant dans les disponibilités et côté client.';
  $('driverPublishDay').value='';$('driverPublishCheckin').value='';$('driverPublishTime').value='';$('driverPublishBoarding').value='';
}
async function driverPayDeposit(id){if(!confirm('Confirmer que la caution a été envoyée à TACLAR ?'))return;await updateDoc(id,{status:'deposit_paid',depositPaid:true,depositPaidAt:Date.now()})}
function logoutDriver(){clearDriverSession();renderPage()}
function renderValidation(){setShell('validation',`<div class="card"><div class="item-top"><div><h2>Validation TACLAR</h2><p>Interface interne : valide les documents, confirme la caution reçue, puis autorise le chauffeur à publier.</p></div><button class="red" onclick="resetTestData()">Réinitialiser test</button></div><div class="notice warning"><strong>Important :</strong> le chauffeur déclare lui-même le dépôt de la caution depuis son espace. TACLAR confirme seulement sa réception.</div><div id="applicationsList" class="list" style="margin-top:14px"></div></div>`);renderApplicationsList()}
function renderApplicationsList(){
  const box=$('applicationsList');if(!box)return;
  const all=apps().filter(a=>a.driverCode);
  const active=all.filter(a=>!a.active).sort((a,b)=>validationPriority(b)-validationPriority(a)||(b.createdAt||0)-(a.createdAt||0));
  const authorized=all.filter(a=>a.active).sort((a,b)=>(b.authorizedAt||b.updatedAt||0)-(a.authorizedAt||a.updatedAt||0));
  if(!all.length){box.innerHTML='<div class="notice">Aucun dossier chauffeur reçu pour le moment.</div>';return}
  box.innerHTML=`<h3>Dossiers à traiter</h3>${active.length?active.map(renderValidationApplication).join(''):'<div class="notice">Aucun dossier actif à traiter.</div>'}<h3 style="margin-top:18px">Dossiers autorisés à publier</h3>${authorized.length?authorized.map(renderAuthorizedApplication).join(''):'<div class="notice">Aucun chauffeur autorisé pour le moment.</div>'}`
}
function validationPriority(a){
  if(a.depositPaid&&!a.depositValidated)return 4;
  if(a.depositValidated&&!a.active)return 3;
  if(a.docsValidated&&!a.depositPaid)return 2;
  return 1;
}
function renderValidationApplication(a){
  return `<details class="item compact-item" ${validationPriority(a)>=3?'open':''}><summary><strong>${a.name}</strong> | Axe : ${a.axis} | Places : ${a.seats} | Statut : ${statusText(a.status)}</summary><div class="facts"><div class="fact"><small>Dossier</small><strong>${a.driverCode}</strong></div><div class="fact"><small>PIN</small><strong>${a.pin||'-'}</strong></div><div class="fact"><small>Téléphone</small><strong>${a.phone}</strong></div><div class="fact"><small>Véhicule</small><strong>${a.vehicle}</strong></div><div class="fact"><small>Plaque</small><strong>${a.plate}</strong></div><div class="fact"><small>Prix axe</small><strong>${money(a.price)}</strong></div><div class="fact"><small>Caution attendue</small><strong>${money(a.deposit)}</strong></div><div class="fact"><small>Permis</small><strong>${a.licenseName||'-'}</strong></div><div class="fact"><small>Identité</small><strong>${a.idCardName||'-'}</strong></div></div><div class="actions"><button onclick="validateDriverDocuments('${a.id}')" ${a.docsValidated?'disabled':''}>Valider les documents</button><button onclick="validateDriverDeposit('${a.id}')" ${!a.depositPaid||a.depositValidated?'disabled':''}>Confirmer caution reçue</button><button class="blue" onclick="authorizeDriver('${a.id}')" ${!a.depositValidated||a.active?'disabled':''}>Autoriser à publier</button></div>${a.docsValidated&&!a.depositPaid?'<div class="notice">Notification simulée : documents approuvés. Le chauffeur doit se reconnecter pour déposer la caution.</div>':''}${a.depositPaid&&!a.depositValidated?'<div class="notice warning">Le chauffeur déclare avoir payé. Vérifie la réception avant de confirmer.</div>':''}${a.depositValidated&&!a.active?'<div class="notice success">Caution reçue. Tu peux autoriser ce chauffeur à publier.</div>':''}</details>`
}
function renderAuthorizedApplication(a){
  return `<details class="item compact-item"><summary><strong>${a.name}</strong> | Axe : ${a.axis} | Places : ${a.seats} | Statut : autorisé à publier</summary><div class="facts"><div class="fact"><small>Dossier</small><strong>${a.driverCode}</strong></div><div class="fact"><small>PIN</small><strong>${a.pin||'-'}</strong></div><div class="fact"><small>Téléphone</small><strong>${a.phone}</strong></div><div class="fact"><small>Véhicule</small><strong>${a.vehicle}</strong></div><div class="fact"><small>Plaque</small><strong>${a.plate}</strong></div></div></details>`
}
async function validateDriverDocuments(id){await updateDoc(id,{status:'docs_validated',docsValidated:true,docsValidatedAt:Date.now()})}
async function validateDriverDeposit(id){await updateDoc(id,{status:'deposit_validated',depositValidated:true,depositValidatedAt:Date.now()})}
async function authorizeDriver(id){await updateDoc(id,{status:'active',active:true,mustRelogin:true,authorizedAt:Date.now(),lastNotification:'Autorisation de publier le trajet'});clearDriverSession()}
function renderPublish(){setShell('publish',`<div class="grid two"><div class="card"><h2>Publier un trajet</h2><p>Outil interne de test. Dans le vrai parcours, le chauffeur publie directement depuis son espace chauffeur connecté.</p><div class="field-grid"><div><label>Chauffeur validé</label><select id="publishDriver"></select></div><div><label>Axe</label><input id="publishAxis" disabled></div><div><label>Véhicule</label><input id="publishVehicle" disabled></div><div><label>Plaque</label><input id="publishPlate" disabled></div><div><label>Places disponibles</label><input id="publishSeats" type="number" min="1"></div><div><label>Prix transport / place</label><input id="publishPrice" disabled></div><div><label>Date de départ</label><input id="publishDay" type="date"></div><div><label>Heure d'enregistrement</label><select id="publishCheckin"></select></div><div><label>Heure de départ</label><select id="publishTime"></select></div><div><label>Point d'embarquement</label><input id="publishBoarding" placeholder="Ex : Gare routière"></div></div><div class="actions"><button id="publishBtn">Publier le trajet</button></div><div id="publishMsg" class="notice hidden"></div></div><div class="card"><h2>Règle</h2><div class="notice success">Un chauffeur peut publier seulement si son dossier et sa caution sont validés.</div></div></div>`);const drivers=activeApps();$('publishDriver').innerHTML='<option value="">-- Choisir chauffeur --</option>'+drivers.map(d=>`<option value="${d.id}">${d.name}</option>`).join('');fillTimeSelect($('publishCheckin'),'-- Heure enregistrement --');fillTimeSelect($('publishTime'),'-- Heure départ --');$('publishDriver').onchange=syncPublishDriver;$('publishBtn').onclick=publishOffer;syncPublishDriver()}
function syncPublishDriver(){const a=activeApps().find(x=>x.id===$('publishDriver').value);['publishAxis','publishVehicle','publishPlate','publishPrice','publishSeats'].forEach(id=>$(id).value='');if(!a)return;$('publishAxis').value=a.axis;$('publishVehicle').value=a.vehicle;$('publishPlate').value=a.plate;$('publishPrice').value=money(a.price);$('publishSeats').value=a.seats}
async function publishOffer(){const a=activeApps().find(x=>x.id===$('publishDriver').value);if(!a){alert('Choisissez un chauffeur validé.');return}const day=$('publishDay').value,checkinTime=$('publishCheckin').value,time=$('publishTime').value,boarding=$('publishBoarding').value.trim(),seats=Number($('publishSeats').value||0);if(!day||!checkinTime||!time||!boarding||seats<1){alert('Complétez date, heures, embarquement et places.');return}await addDoc({type:'offer',driverAppId:a.id,driver:a.name,phone:a.phone,vehicle:a.vehicle,plate:a.plate,axis:a.axis,seats,booked:0,price:a.price,day,checkinTime,time,boarding,status:'Disponible',source:'v30'});$('publishMsg').className='notice success';$('publishMsg').textContent='Trajet publié. Il apparaît maintenant côté client et booking.';$('publishDay').value='';$('publishCheckin').value='';$('publishTime').value='';$('publishBoarding').value=''}
function renderActiveDrivers(){const box=$('activeDriversBox');if(!box)return;const list=activeApps();box.innerHTML=list.length?list.map(a=>`<div class="item"><strong>${a.name}</strong><br>${a.axis}<br>${a.vehicle} - ${a.plate}</div>`).join(''):'<div class="notice">Aucun chauffeur actif pour le moment.</div>'}
function renderBooking(){const all=offers();setShell('booking',`<div class="card"><h2>Liste des chauffeurs / disponibilités</h2><p>Vue publique des disponibilités publiées. Les échanges clients sont traités dans l’espace chauffeur connecté.</p><div id="bookingList" class="list"></div></div>`);const box=$('bookingList');if(!all.length){box.innerHTML='<div class="notice">Aucune disponibilité publiée.</div>';return}const sorted=[...all].sort((a,b)=>{const score=o=>freeSeats(o)<=0?0:reqsForOffer(o.id).some(r=>r.status==='pending')?3:2;return score(b)-score(a)||(b.createdAt||0)-(a.createdAt||0)});box.innerHTML=sorted.map(renderBookingOffer).join('')}
function renderBookingOffer(o){const pending=reqsForOffer(o.id).filter(r=>r.status==='pending').reduce((s,r)=>s+Number(r.seats||1),0);const confirmed=reqsForOffer(o.id).filter(r=>['confirmed','paid'].includes(r.status)).reduce((s,r)=>s+Number(r.seats||1),0);return `<div class="item ${freeSeats(o)>0?'selected':''}"><div class="item-top"><div><div class="name">${o.driver}</div><div class="axis-name">${o.axis}</div></div><span class="badge ${freeSeats(o)<=0?'full':'ok'}">${freeSeats(o)<=0?'Complet':freeSeats(o)+' place(s) libres'}</span></div><div class="facts booking-facts"><div class="fact"><small>Jour</small><strong>${o.day}</strong></div><div class="fact"><small>Enregistrement</small><strong>${o.checkinTime}</strong></div><div class="fact"><small>Départ</small><strong>${o.time}</strong></div><div class="fact"><small>Véhicule</small><strong>${o.vehicle}</strong></div><div class="fact"><small>Plaque</small><strong>${o.plate}</strong></div><div class="fact"><small>Prix / place</small><strong>${money(o.price)}</strong></div><div class="fact"><small>Demandes en attente</small><strong>${pending}</strong></div><div class="fact"><small>Places confirmées</small><strong>${confirmed}</strong></div><div class="fact"><small>Embarquement</small><strong>${o.boarding}</strong></div></div></div>`}
function renderBookingRequest(r,o){const passengerList=(r.passengerNames||[r.clientName]).join(', ');const reasonId='reason-'+r.id;return `<div class="item"><div class="item-top"><div><strong>${r.groupLeader||r.clientName}</strong><div class="muted">${r.clientPhone} · ${r.seats} place(s) · ${r.requestCode||''} · ${r.createdLabel||''}</div><div>${passengerList}</div></div><span class="badge ${r.status==='paid'?'ok':r.status==='pending'?'warn':'full'}">${statusText(r.status)}</span></div>${r.status==='paid'?`<div class="notice success">Commission TACLAR payée. Rendez-vous le ${o.day} à ${o.checkinTime} au point d'embarquement : ${o.boarding}. Départ prévu : ${o.time}.</div>`:''}${r.status==='refused'?`<div class="notice danger"><strong>Demande refusée.</strong> Motif : ${r.refusalReason||'Non précisé'}.</div>`:''}<div class="actions"><button onclick="updateDoc('${r.id}',{status:'confirmed'})" ${r.status!=='pending'?'disabled':''}>Confirmer place</button><select id="${reasonId}" ${r.status!=='pending'?'disabled':''}><option value="Véhicule déjà complet">Véhicule déjà complet</option><option value="Départ annulé">Départ annulé</option><option value="Horaire modifié">Horaire modifié</option><option value="Client à rappeler">Client à rappeler</option><option value="Autre motif">Autre motif</option></select><button class="ghost" onclick="refuseRequest('${r.id}','${reasonId}')" ${r.status!=='pending'?'disabled':''}>Refuser</button><button class="red" onclick="deleteDocHard('${r.id}')" ${r.status==='paid'?'disabled':''}>Supprimer erreur</button></div></div>`}
async function refuseRequest(id,reasonId){
  const select=$(reasonId);
  const reason=select?select.value:'Motif non précisé';
  if(!confirm('Refuser cette demande et envoyer le motif au client ?'))return;
  await updateDoc(id,{status:'refused',refusalReason:reason,refusedAt:Date.now()});
}
function renderClient(){setShell('client',`<div class="grid two"><div class="card"><h2>Client - chercher un trajet</h2><p>Le client choisit un axe, sélectionne un chauffeur et demande une ou plusieurs places.</p><div class="field-grid"><div><label>Axe recherché</label><select id="clientAxis"></select></div><div><label>Mode de paiement TACLAR</label><select id="paymentMode"><option value="single">Individuel - une place</option><option value="group">Groupe/famille - plusieurs places</option></select></div><div><label>Nom du client / responsable</label><input id="clientName" placeholder="Ex : Arielle Mba"></div><div><label>Téléphone responsable</label><input id="clientPhone" placeholder="Ex : +241 66 12 34 56"></div><div id="groupSeatsWrap" class="hidden"><label>Nombre de places à réserver</label><input id="groupSeats" type="number" min="2" max="6" value="2"></div></div><div id="groupNamesWrap" class="hidden"><label>Noms des passagers du groupe</label><div id="groupNames"></div></div><div id="clientOffers" class="list" style="margin-top:12px"></div></div><div class="card"><h2>Suivi client</h2><div class="notice"><div class="row"><span>Frais TACLAR</span><strong>${money(taclarFee)} / place</strong></div><div class="row"><span>Transport</span><strong>Payé au chauffeur</strong></div><div class="row"><span>Infos complètes</span><strong>Après paiement TACLAR</strong></div></div><div id="toPayBox" class="list"></div><h3 style="margin-top:14px">Mes réservations payées</h3><div id="paidBox" class="list"></div></div></div>`);fillAxisSelect($('clientAxis'));$('clientAxis').onchange=renderClientOffers;$('paymentMode').onchange=()=>{syncGroupFields();renderClientOffers()};$('groupSeats').oninput=renderGroupNameInputs;syncGroupFields();renderClientOffers();renderPayments()}
function syncGroupFields(){const group=$('paymentMode').value==='group';$('groupSeatsWrap').classList.toggle('hidden',!group);$('groupNamesWrap').classList.toggle('hidden',!group);if(group)renderGroupNameInputs()}
function renderGroupNameInputs(){const count=Math.max(2,Number($('groupSeats').value||2));$('groupSeats').value=count;const existing=[...document.querySelectorAll('.groupName')].map(i=>i.value);$('groupNames').innerHTML=Array.from({length:count},(_,i)=>`<input class="groupName" placeholder="Nom passager ${i+1}" value="${existing[i]||''}" style="margin-bottom:8px">`).join('')}
function renderClientOffers(){const axis=$('clientAxis').value,box=$('clientOffers');if(!axis){box.innerHTML='<div class="notice">Choisissez un axe pour afficher les chauffeurs disponibles.</div>';return}const list=offers().filter(o=>o.axis===axis&&o.status==='Disponible').sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));if(!list.length){box.innerHTML='<div class="notice warning">Aucun trajet disponible pour cet axe.</div>';return}box.innerHTML=list.map(o=>{const selected=selectedOfferId===o.id;const free=freeSeats(o);const isFull=free<=0;return `<div class="item ${selected&&!isFull?'selected':''}"><div class="item-top"><div><div class="name">${o.driver}</div><div class="axis-name">${o.axis}</div></div><span class="badge ${isFull?'full':'ok'}">${isFull?'Complet':free+' place(s)'}</span></div>${isFull?`<div class="notice warning">Ce véhicule est complet. Les détails passagers restent privés.</div>`:selected?`<div class="facts"><div class="fact"><small>Date</small><strong>${o.day}</strong></div><div class="fact"><small>Enregistrement</small><strong>${o.checkinTime}</strong></div><div class="fact"><small>Départ</small><strong>${o.time}</strong></div><div class="fact"><small>Voiture</small><strong>${o.vehicle}</strong></div><div class="fact"><small>Prix / place</small><strong>${money(o.price)}</strong></div></div><div class="notice"><strong>Avant paiement TACLAR :</strong> téléphone masqué (${phoneMask(o.phone)}), point d'embarquement général : ${o.boarding}.</div>`:`<div class="notice">Cliquez sur Voir les détails pour afficher le jour, l'heure, le véhicule, le prix et le point d'embarquement.</div>`}<div class="actions"><button class="ghost" onclick="selectedOfferId='${selected?'':o.id}';renderClientOffers()" ${isFull?'disabled':''}>${selected&&!isFull?'Masquer les détails':'Voir les détails'}</button><button onclick="requestPlaces('${o.id}')" ${isFull?'disabled':''}>${$('paymentMode').value==='group'?'Demander les places':'Demander une place'}</button></div></div>`}).join('')}
async function requestPlaces(offerId){const o=offers().find(x=>x.id===offerId);const mode=$('paymentMode').value,name=$('clientName').value.trim(),phone=$('clientPhone').value.trim();if(!name||!phone){alert('Remplissez le nom du responsable et son téléphone.');return}let passengerNames=[name],seats=1;if(mode==='group'){seats=Math.max(2,Number($('groupSeats').value||2));passengerNames=[...document.querySelectorAll('.groupName')].map(i=>i.value.trim()).filter(Boolean);if(passengerNames.length!==seats){alert('Remplissez les noms des '+seats+' passagers du groupe.');return}}if(seats>freeSeats(o)){alert('Il ne reste pas assez de places dans ce véhicule.');return}await addDoc({type:'request',offerId:o.id,clientName:name,clientPhone:phone,groupLeader:name,paymentMode:mode,seats,passengerNames,status:'pending',requestCode:'REQ-'+Math.floor(1000+Math.random()*9000),createdLabel:nowLabel()});alert('Demande envoyée au chauffeur pour confirmation.');$('clientName').value='';$('clientPhone').value='';if(mode==='group')renderGroupNameInputs()}
function renderPayments(){const toPay=requests().filter(r=>r.status==='confirmed');const refused=requests().filter(r=>r.status==='refused').sort((a,b)=>(b.refusedAt||0)-(a.refusedAt||0));$('toPayBox').innerHTML=(toPay.length?toPay.map(r=>{const o=offers().find(x=>x.id===r.offerId)||{};return `<div class="item"><strong>${r.groupLeader||r.clientName}</strong><div>${r.seats} place(s) confirmée(s) avec ${o.driver||'-'}</div><div class="row"><span>Total frais TACLAR</span><strong>${money(Number(r.seats||1)*taclarFee)}</strong></div><button class="orange" onclick="updateDoc('${r.id}',{status:'paid',paidAt:Date.now()})">Payer commission TACLAR</button></div>`}).join(''):'<div class="notice">Aucune place confirmée en attente de paiement.</div>')+(refused.length?`<h3 style="margin-top:14px">Demandes refusées</h3>${refused.map(r=>{const o=offers().find(x=>x.id===r.offerId)||{};return `<div class="item"><strong>${r.groupLeader||r.clientName}</strong><div>${o.driver||'Chauffeur'} - ${o.axis||'-'}</div><div class="notice danger"><strong>Demande non acceptée.</strong><br>Motif : ${r.refusalReason||'Non précisé'}.</div></div>`}).join('')}`:'');const paid=requests().filter(r=>r.status==='paid').sort((a,b)=>(b.paidAt||0)-(a.paidAt||0));$('paidBox').innerHTML=paid.length?paid.map(r=>{const o=offers().find(x=>x.id===r.offerId)||{};return `<div class="item"><strong>Reçu ${r.paymentMode==='group'?'groupe':'individuel'}</strong><div class="row"><span>Responsable</span><strong>${r.groupLeader||r.clientName}</strong></div><div class="row"><span>Passagers</span><strong>${(r.passengerNames||[]).join(', ')}</strong></div><div class="row"><span>Axe</span><strong>${o.axis||'-'}</strong></div><div class="row"><span>Chauffeur</span><strong>${o.driver||'-'}</strong></div><div class="row"><span>Téléphone chauffeur</span><strong>${o.phone||'-'}</strong></div><div class="row"><span>Enregistrement</span><strong>${o.checkinTime||'-'}</strong></div><div class="row"><span>Départ</span><strong>${o.time||'-'}</strong></div><div class="row"><span>Embarquement</span><strong>${o.boarding||'-'}</strong></div><div class="row"><span>Total frais TACLAR</span><strong>${money(Number(r.seats||1)*taclarFee)}</strong></div><button class="blue" onclick="window.print()">Télécharger / imprimer le reçu</button></div>`}).join(''):'<div class="notice">Les informations complètes du chauffeur apparaissent ici après paiement.</div>'}

document.addEventListener('DOMContentLoaded',initFirebase);
